export type PendukungTimses = {
  pendukung_id: string;
  nik: number;
  name: string;
  phone: string;
  kabupaten: string;
  kecamatan: string;
  desa: string;
  tps: string;
  address: string;
  aktif: boolean;
  created_by: number;
  created_at: string;
  updated_at: string;
  kabupaten_name: string;
  kecamatan_name: string;
  desa_name: string;
  kabupaten_code: string;
  kecamatan_code: string;
  desa_code: string;
};
